// Copyright 2012 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

/*
Package secretbox encrypts and authenticates small messages.

Secretbox uses XSalsa20 and Poly1305 to encrypt and authenticate messages with
secret-key cryptography. The length of messages is not hidden.

It is the caller's responsibility to ensure the uniqueness of nonces—for
example, by using nonce 1 for the first message, nonce 2 for the second
message, etc. Nonces are long enough that randomly generated nonces have
negligible risk of collision.

Messages should be small because:

1. The whole message needs to be held in memory to be processed.

2. Using large messages pressures implementations on small machines to decrypt
and process plaintext before authenticating it. This is very dangerous, and
this API does not allow it, but a protocol that uses excessive message sizes
might present some implementations with no other choice.

3. Fixed overheads will be sufficiently amortised by messages as small as 8KB.

4. Performance may be improved by working with messages that fit into data caches.

Thus large amounts of data should be chunked so that each message is small.
(Each message still needs a unique nonce.) If in doubt, 16KB is a reasonable
chunk size.

This package is interoperable with NaCl: https://nacl.cr.yp.to/secretbox.html.
*/
package unclassified // import "golang.org/x/crypto/nacl/secretbox"

import (
	"errors"
	"unsafe"

	"golang.org/x/crypto/salsa20/salsa"
)

// Overhead is the number of bytes of overhead when boxing a message.
const Overhead = TagSize

// setup produces a sub-key and Salsa20 counter given a nonce and key.
func setup(subKey *[KeySize]byte, counter *[16]byte, nonce *[NonceSize]byte, key *[KeySize]byte) {
	// We use XSalsa20 for encryption so first we need to generate a
	// key and nonce with HSalsa20.
	var hNonce [16]byte
	copy(hNonce[:], nonce[:])
	salsa.HSalsa20(subKey, &hNonce, key, &salsa.Sigma)

	// The final 8 bytes of the original nonce form the new nonce.
	copy(counter[:], nonce[16:])
}

// sliceForAppend takes a slice and a requested number of bytes. It returns a
// slice with the contents of the given slice followed by that many bytes and a
// second slice that aliases into it and contains only the extra bytes. If the
// original slice has sufficient capacity then no allocation is performed.
func sliceForAppend(in []byte, n int) (head, tail []byte) {
	if total := len(in) + n; cap(in) >= total {
		head = in[:total]
	} else {
		head = make([]byte, total)
		copy(head, in)
	}
	tail = head[len(in):]
	return
}

func anyOverlap(x, y []byte) bool {
	return len(x) > 0 && len(y) > 0 &&
		uintptr(unsafe.Pointer(&x[0])) <= uintptr(unsafe.Pointer(&y[len(y)-1])) &&
		uintptr(unsafe.Pointer(&y[0])) <= uintptr(unsafe.Pointer(&x[len(x)-1]))
}

// Seal appends an encrypted and authenticated copy of message to out, which
// must not overlap message. The key and nonce pair must be unique for each
// distinct message and the output will be Overhead bytes longer than message.
func Seal(out, message []byte, nonce *[NonceSize]byte, key *[KeySize]byte) []byte {
	var subKey [KeySize]byte
	var counter [16]byte
	setup(&subKey, &counter, nonce, key)

	// The Poly1305 key is generated by encrypting KeySize bytes of zeros. Since
	// Salsa20 works with 64-byte blocks, we also generate KeySize bytes of
	// keystream as a side effect.
	var firstBlock [64]byte
	salsa.XORKeyStream(firstBlock[:], firstBlock[:], &counter, &subKey)

	var poly1305Key [KeySize]byte
	copy(poly1305Key[:], firstBlock[:])

	ret, out := sliceForAppend(out, len(message)+TagSize)
	if anyOverlap(out, message) {
		panic("nacl: invalid buffer overlap")
	}

	// We XOR up to KeySize bytes of message with the keystream generated from
	// the first block.
	firstMessageBlock := message
	if len(firstMessageBlock) > KeySize {
		firstMessageBlock = firstMessageBlock[:KeySize]
	}

	tagOut := out
	out = out[TagSize:]
	for i, x := range firstMessageBlock {
		out[i] = firstBlock[KeySize+i] ^ x
	}
	message = message[len(firstMessageBlock):]
	ciphertext := out
	out = out[len(firstMessageBlock):]

	// Now encrypt the rest.
	counter[8] = 1
	salsa.XORKeyStream(out, message, &counter, &subKey)

	var tag [TagSize]byte
	hash := poly1305_New(&poly1305Key)
	hash.Write(ciphertext)
	hash.Sum(tag[:0])
	copy(tagOut, tag[:])

	return ret
}

// Open authenticates and decrypts a box produced by Seal and appends the
// message to out, which must not overlap box. The output will be Overhead
// bytes smaller than box.
func Open(out, box []byte, nonce *[NonceSize]byte, key *[KeySize]byte) ([]byte, error) {
	if len(box) < Overhead {
		return nil, errors.New("Open:ciphertext is too short")
	}

	var subKey [KeySize]byte
	var counter [16]byte
	setup(&subKey, &counter, nonce, key)

	// The Poly1305 key is generated by encrypting KeySize bytes of zeros. Since
	// Salsa20 works with 64-byte blocks, we also generate KeySize bytes of
	// keystream as a side effect.
	var firstBlock [64]byte
	salsa.XORKeyStream(firstBlock[:], firstBlock[:], &counter, &subKey)

	var poly1305Key [KeySize]byte
	copy(poly1305Key[:], firstBlock[:])
	ciphertext := box[Overhead:]
	
	hash := poly1305_New(&poly1305Key)
	hash.Write(ciphertext)

	if !hash.Verify(box[:Overhead]) {
		return nil, errors.New("Open:ciphertext authentication failed")
	}

	ret, out := sliceForAppend(out, len(ciphertext))
	if anyOverlap(out, box) {
		panic("nacl: invalid buffer overlap")
	}

	// We XOR up to KeySize bytes of box with the keystream generated from
	// the first block.
	firstMessageBlock := ciphertext
	if len(firstMessageBlock) > KeySize {
		firstMessageBlock = firstMessageBlock[:KeySize]
	}
	for i, x := range firstMessageBlock {
		out[i] = firstBlock[KeySize+i] ^ x
	}

	ciphertext = ciphertext[len(firstMessageBlock):]
	out = out[len(firstMessageBlock):]

	// Now decrypt the rest.
	counter[8] = 1
	salsa.XORKeyStream(out, ciphertext, &counter, &subKey)

	return ret, nil
}
